microsoft/service-fabric-services-and-actors-dotnet

src/Microsoft.ServiceFabric.Services/Runtime/StatefulServiceBase.cs
src/Microsoft.ServiceFabric.Services/Runtime/StatelessService.cs

According to issue #9 I've added null-check arguments. Please review.

Added null-check arguments to Service constructors.

---

src/Microsoft.ServiceFabric.Actors/Runtime/ActorReminder.cs

Fix to issue #13 Please review

Actor reminders use a 64-bit integer

---

src/Microsoft.ServiceFabric.Actors/Client/ActorProxy.cs
src/Microsoft.ServiceFabric.Actors/Client/ActorProxyEventExtensions.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorBase.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorManager.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorRuntime.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorService.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorTimer.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ReminderCompletedDataSerializer.cs
src/Microsoft.ServiceFabric.Actors/Runtime/VolatileActorStateTable.cs
src/Microsoft.ServiceFabric.Services.Remoting/Builder/ProxyBase.cs
src/Microsoft.ServiceFabric.Services.Wcf/Communication/Wcf/WcfRemoteExceptionInformation.cs
src/Microsoft.ServiceFabric.Services/Communication/Client/ServicePartitionClient.cs
test/unittests/Microsoft.ServiceFabric.Actors.Tests/Runtime/Volatile/VolatileStateProviderTestBase.cs

Fixed some async/await misuses. Please review. Thank you in advance

Fixed async/await misuses

---

src/Microsoft.ServiceFabric.Services.Remoting/Runtime/ServiceRemotingExtensions.cs
src/Microsoft.ServiceFabric.Services.Remoting/ServiceRemotingProviderAttribute.cs

Documentation: V1 is soon to be deprecated, not V2

Documentation: V1 is soon to be deprecated, not V2

---

src/Microsoft.ServiceFabric.Services/Communication/Client/CommunicationClientFactoryBase.cs

- changed internal constructor to be protected
- added xml comments to newly converted constructor

Converted the internal constructor on CommunicationClientFactoryBase to protected

---

src/Microsoft.ServiceFabric.Services/Runtime/ServiceRuntime.cs

Fix modifiers declaration order

---

src/Microsoft.ServiceFabric.Actors/Client/ActorProxy.cs
src/Microsoft.ServiceFabric.Actors/Remoting/ActorDataContractSurrogate.cs
src/Microsoft.ServiceFabric.Actors/Remoting/V1/Builder/ActorCodeBuilder.cs
src/Microsoft.ServiceFabric.Actors/Remoting/V1/Client/ActorEventSubscriberManager.cs
src/Microsoft.ServiceFabric.Actors/Remoting/V1/Client/ActorProxyFactory.cs
src/Microsoft.ServiceFabric.Actors/Remoting/V2/Builder/ActorCodeBuilder.cs
src/Microsoft.ServiceFabric.Actors/Remoting/V2/Client/ActorEventSubscriberManager.cs
src/Microsoft.ServiceFabric.Actors/Remoting/V2/Client/ActorProxyFactory.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorStateProviderHelper.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorStateProviderSerializer.cs
src/Microsoft.ServiceFabric.Services.Remoting/V1/Builder/ServiceCodeBuilder.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/Builder/ServiceCodeBuilder.cs

Renamed field Singleton to Instance

---

build.ps1
properties/service_fabric_managed_common.props

Updating build script and pdb info

Updating build script and pdb info

---

nuprojs/Microsoft.ServiceFabric.Actors/Microsoft.ServiceFabric.Actors.nuproj
properties/service_fabric_managed_common.props
properties/service_fabric_nuget.props
src/Microsoft.ServiceFabric.Actors/Microsoft.ServiceFabric.Actors.csproj
src/Microsoft.ServiceFabric.Actors/Runtime/ActorStateProviderHelper.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ReliableCollectionsActorStateProvider.cs
src/Microsoft.ServiceFabric.Services.Remoting/Microsoft.ServiceFabric.Services.Remoting.csproj
src/Microsoft.ServiceFabric.Services/Microsoft.ServiceFabric.Services.csproj
src/netcore/Microsoft.ServiceFabric.Actors/Microsoft.ServiceFabric.Actors_netcore.csproj
src/netcore/Microsoft.ServiceFabric.Services.Remoting/Microsoft.ServiceFabric.Services.Remoting_netcore.csproj
src/netcore/Microsoft.ServiceFabric.Services/Microsoft.ServiceFabric.Services_netcore.csproj

Updating code for 3.1.262 sdk version (6.2 runtime)

Updating code for 3.1.262 sdk version (6.2 runtime)

---

src/Microsoft.ServiceFabric.Services.Remoting/Client/IServiceProxyFactory.cs
src/Microsoft.ServiceFabric.Services.Remoting/SR.Designer.cs
src/Microsoft.ServiceFabric.Services.Remoting/SR.resx
src/Microsoft.ServiceFabric.Services.Remoting/V1/Client/ServiceProxyFactory.cs

Extend IServiceProxyFactory with CreateNonIServiceProxy method

---

src/netstandard/FabActUtil/Microsoft.ServiceFabric.Actors.targets

Fix build error when $(AssemblyName) is set

---

src/Microsoft.ServiceFabric.Services.Remoting/Client/ServiceProxyFactory.cs

Today we are not setting correct listenerName for Service Remoting V2_1 if we are using provider attributes .

Overiding ListenerName for Remoting V2_1

---

properties/service_fabric_common.props
src/FabActUtil/Tool.cs
src/FabActUtil/ToolArguments.cs
src/Microsoft.ServiceFabric.Actors/Generator/ManifestGenerator.cs

Handling assembly load issues in FabActUtil.

Handling assembly load issues in FabActUtil.

---

properties/service_fabric_common.props
src/Microsoft.ServiceFabric.Actors/Runtime/ActorService.cs

Fix CloseAsync telemetry for Actors

---

properties/service_fabric_common.props
src/Microsoft.ServiceFabric.Services/Runtime/ServiceHelper.cs

Handling OOM while reprting health for Unhandled Exception from user's RunAsync code.

---

src/Microsoft.ServiceFabric.Services/Runtime/ServiceHelper.cs
src/Microsoft.ServiceFabric.Services/Runtime/StatefulServiceReplicaAdapter.cs
src/Microsoft.ServiceFabric.Services/Runtime/StatelessServiceInstanceAdapter.cs
test/unittests/Microsoft.ServiceFabric.Services.Tests/Utility.cs

Fixes https://github.com/microsoft/service-fabric-services-and-actors-dotnet/issues/249

Adding traces around User service close async and reducing ttl for slow operation completions

---

nuget.config

Added clear statement

---

src/Microsoft.ServiceFabric.Services/Runtime/StatefulServiceReplicaAdapter.cs

The PR consists of the fix for the ChangeRole issue posted at [https://github.com/microsoft/service-fabric/issues/1058](https://github.com/microsoft/service-fabric/issues/1058)
The ChangeRole issue happens when is Primary replica is becoming None (i.e., being closed). In this case, the ChangeRole procedure can get stuck, if the ChangeRole procedure is triggered when the RunAsync() is committing a transaction. In this case, the Native stack can successfully complete ChangeRole. However, the managed stack will not complete ChangeRole until RunAsync is canceled. As RunAsync detects that the role of native stack is not Primary, the RunAsync can never complete its commit and will not be canceled successfully. This creates a deadlock situation.
We reproduced the ChangeRole issue on a local …

Fix of ChangeRole being stuck in RunAsync

---

src/Microsoft.ServiceFabric.Services.Remoting/FabricTransport/FabricTransportRemotingSettings.cs
src/Microsoft.ServiceFabric.Services.Remoting/FabricTransport/Runtime/FabricTransportRemotingListenerSettings.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/Client/ExceptionConversionHandler.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/FabricTransport/Client/FabricTransportServiceRemotingClient.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/FabricTransport/Runtime/FabricTransportServiceRemotingListener.cs
test/unittests/Microsoft.ServiceFabric.Actors.Tests/ExceptionConvertors/FabricActorExceptionTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/CompatScenarioTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/CustomConvertorTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/FabricExceptionConvertorTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/SystemExceptionConvertorTest.cs

Testing performed.
https://sftestinfra/Run/RunView/8054f19a-c838-4caf-91b4-d6049898e9dd

Regression bug fixes caused due to Exception serialization feature changes.

---

src/Microsoft.ServiceFabric.Actors/Runtime/ActorManager.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorReminder.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorTimer.cs
src/Microsoft.ServiceFabric.Actors/Runtime/VolatileLogicalTimeManager.cs
src/Microsoft.ServiceFabric.Services/Communication/Client/CommunicationClientCache.cs

Related to issue  #257 
This fix was applied in many places in the .net core code
some examples:
aspnet/SignalR#2904
aspnet/Razor#2565

Don't capture AsyncLocals onto Timers

---

src/Microsoft.ServiceFabric.Services/Client/ServicePartitionResolver.cs

Pass the cancellation token to the resolver func.
Fixes #348

Pass cancellation token to the resolver

---

properties/service_fabric_managed_common.props

This would enable building SF apps to target arm64.

Build Actors Services packages with AnyCPU configurations

---

properties/service_fabric_common.props

Internal ADO work item: https://dev.azure.com/msazure/One/_workitems/edit/27480377

Bump build version as 7.0.8 is already produced

---

properties/service_fabric_common.props

This commit is an addition to the previous commit.

Bumping version of SF.ActorsServices.Internal

---

properties/service_fabric_common.props
src/Microsoft.ServiceFabric.Actors.KVSToRCMigration/Microsoft.ServiceFabric.Actors.KVSToRCMigration.csproj
src/netstandard/Microsoft.ServiceFabric.Actors.KVSToRCMigration/Microsoft.ServiceFabric.Actors.KVSToRCMigration_netstandard.csproj
test/unittests/Microsoft.ServiceFabric.Actors.StateMigration.Tests/Microsoft.ServiceFabric.Actors.StateMigration.Tests.csproj

This PR addresses unaddressed comments form #389.
Internal ADO work item: https://dev.azure.com/msazure/One/_workitems/edit/29603592

Updating versions of transitive dependencies

---

properties/service_fabric_common.props

Version of SF.ActorsServices.Internal is updated so it can be published to internal feed.

Bump version of SF.ActorsServices.Internal

---

src/Microsoft.ServiceFabric.Diagnostics/Microsoft.ServiceFabric.Diagnostics.csproj

Diagnostics project needs documentation to be generated during build.

Generate documentation for Diagnostics project
