microsoft/service-fabric-services-and-actors-dotnet

README.md

The links to the service-fabric repo in the README.md seem to point to an invalid location. This should resolve that.

Fix contributing/readme links

---

src/Microsoft.ServiceFabric.Actors/Runtime/MockActorManager.cs
src/Microsoft.ServiceFabric.Services/Communication/Client/CommunicationClientCache.cs
src/Microsoft.ServiceFabric.Services/Runtime/RuntimeContext.cs
src/Microsoft.ServiceFabric.Services/Runtime/StatefulServiceReplicaFactory.cs
src/Microsoft.ServiceFabric.Services/Runtime/StatelessServiceInstanceFactory.cs

The `MockActorManager` and  `RuntimeContext` class containing IDisposable members does not itself implement IDisposable. 
Also the `traceId` field is used before it is initialized in constructor.
Please review.

Added implementation of IDisposable to classes that contains IDisposable members

---

src/Microsoft.ServiceFabric.Services.Remoting/Client/ServiceProxyFactory.cs

`retrySettings` are not passed for default V2 listener in `ServiceProxyFactory`

Retry settings not sent for netcoreclr

---

code.sln
src/FabActUtil/Tool.cs
src/Microsoft.ServiceFabric.Services.Remoting/Client/ServiceProxyFactory.cs
src/Microsoft.ServiceFabric.Services.Remoting/Runtime/ServiceRemotingExtensions.cs
src/Microsoft.ServiceFabric.Services.Wcf/Communication/Wcf/WcfRemoteExceptionInformation.cs

The code.sln should use the .editorconfig file in the same directory. Few minor coding style fixes.

Use the correct .editorconfig file, additional cleanup

---

src/Microsoft.ServiceFabric.Actors/Runtime/ActorRuntime.cs

Small change to make intellisense a bit nicer. Just something I stumbled upon...
Before (note the space between `repre` and `sents`:

Fix return information in intellisense

---

src/Microsoft.ServiceFabric.Actors/Remoting/V2/ActorRemotingWrappingDataContractSerializationProvider.cs

Impact Cases are where IActor is been passed as a parameter to an IActor interface method. 
Customer sees the serializationExceptions while invoking remoting Api.

Added ActorReference type to Actor KnownTypes

---

properties/service_fabric_common.props
src/Microsoft.ServiceFabric.Services/Communication/Client/CommunicationClientFactoryBase.cs

For the cases where user ClientFactory implementation is implementing IDisposable, they can now extend the Dispose implementation by overriding it.

Making Dispose Method virtual

---

src/Microsoft.ServiceFabric.Actors/Runtime/ActorStateProviderSerializer.cs

ActorStateProviderSerializer was not using ActorDataContractSurrogate in DotNetCoreClr. This prevents serialization of actor proxies to state. Modified ActorStateProviderSerializer  to use the existing (and currently unreferenced) ActorStateProviderHelper.CreateDataContractSerializer static method, which handles ActorDataContractSurrogate correctly for DotNetCoreClr.
Related to the fix for https://github.com/Azure/service-fabric-issues/issues/590

Fixed ActorStateProviderSerializer to use ActorDataContractSurrogate for DotNetCoreClr

---

src/Microsoft.ServiceFabric.Services/Runtime/StatelessService.cs

Addresses a typo in `will be appear` part by removing `be` and prefixing the sentence with `Furthermore` to improve readability.
Spotted at: https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.runtime.statelessservice.runasync?view=azure-dotnet#remarks.

Improve description of RunAsync method

---

src/Microsoft.ServiceFabric.Services.Wcf/Communication/Wcf/Runtime/WcfAsyncThreadExceptionHandler.cs
src/Microsoft.ServiceFabric.Services.Wcf/Communication/Wcf/Runtime/WcfCommunicationListener.cs

PR to resolve #198 & #67 
Code change passes service implementation instance (or type depending on constructor used) down the call chain where it is used to create service endpoint instances which in turn is used by service host to configure and activate WCF service.
Local test confirms fix with WCF Service Host within Service Fabric applies configuration declared by `[ServiceBehavior(...)]` attribute, like implicit transaction scope.

Resolve issue #198 - WCF Host fails to apply transaction configuration of WCF configuration for service

---

src/netstandard/FabActUtil/Microsoft.ServiceFabric.Actors.targets

runtime config not required when rid -> "win7-x64"

Disabling RuntimeConfig generation for FabactUtil when rid=win7-x64

---

src/Microsoft.ServiceFabric.Services.Remoting/Diagnostic/PerformanceCounterInstanceNameBuilder.cs

See issue: https://github.com/microsoft/service-fabric-services-and-actors-dotnet/issues/234
Multiple IService implementations causing 'System.DivideByZeroException' in ServiceRemotingMessageDispatcher

Fix System.DivideByZeroException in PerformanceCounterInstanceNameBuilder.ComputeTruncatedMethodName for overloaded service methods

---

src/Microsoft.ServiceFabric.Actors/Runtime/ActorManager.cs

I encounter issue in our project we are updating existing reminder by calling RegisterReminderAsync and it works well. The issue we notice is memory usage increase after investigating we saw that the RC was ActorReminders waiting in the finilizer queue.
Reviewing the code I saw that on update reminder we create new reminder and just call CancelTimer on the "old" one. I suggest that on update we can just Dispose the "old" reminder which will suppress finalizers.

dispose actor reminder in case of update

---

src/Microsoft.ServiceFabric.Services/Runtime/StatelessServiceInstanceAdapter.cs

Communication Listeners were not getting closed when exception was being thrown from users implementation of onOpenAsync. Fix closes the listeners gracefully.
Fix for [Bug-1057](https://github.com/microsoft/service-fabric/issues/1057)

Fix: StatelessServiceInstanceAdapter to solve onOpenAsync bug

---

src/Microsoft.ServiceFabric.Services.Remoting/V2/Builder/MethodDispatcherBuilder.cs

Testing performed
1) Manually tested E2E with Actor/Stateless apps targeting Net6.0 framework
2) Ran Windows.SDK.Functionals, Windows.SDK.DotNetStd.Functionals and Windows.SDK.NetCore.Functionals test suites

Fix ILGeneration to pass right parameters of GetParameter api

---

src/FabActUtil/Generator/ManifestGenerator.cs

LocalStoreConfigSection in Settings.xml is being removed for Actor service during build. However this config should be preserved. Also this is no longer required to be part of extensions inside servicemanifest.xml.

LocalStoreConfigFix

---

src/netstandard/FabActUtil/Microsoft.ServiceFabric.Actors.targets

.NET 6 doesn't create runtimeconfig.dev.json by default  See:  https://github.com/dotnet/sdk/issues/16818
This crashes the build of Service fabric projects that use .NET 6 services/actors.
I've created the issues at : https://github.com/microsoft/service-fabric/issues/1289

Check if runtimeconfig.dev.json exists

---

src/Microsoft.ServiceFabric.Actors/Runtime/ActorStateProviderHelper.cs
src/Microsoft.ServiceFabric.Actors/Runtime/KvsActorStateProviderBase.cs

Modifying actor enumeration for KVS to take into account the different ordering for actors between KVS and RC.
Tested locally with 5L actors

Modifying actor enumeration for KVS

---

src/Microsoft.ServiceFabric.Actors.KVSToRCMigration/MigrationConstants.cs
src/Microsoft.ServiceFabric.Actors.KVSToRCMigration/MigrationUtility.cs
src/Microsoft.ServiceFabric.Actors.KVSToRCMigration/TargetMigrationOrchestrator.cs

Bug description:
For manual mode migration, if a failover happens during downtime phase, while resuming migration catchup iterations are resumed since the flag _isDowntimeAllowed = true_ is stored in-memory and lost during the failover
Fix:
_isDowntimeAllowed_ is stored in metadata dict and its value is checked if phase==catchup while resuming migration after a failover.

Manual mode migration bug fix

---

src/Microsoft.ServiceFabric.Services.Remoting/Description/ServiceInterfaceDescription.cs

The PR fixes a trivial bug when an incorrect error message was picked up from the resources.

Update ServiceInterfaceDescription to use correct error message when the interface isn't IService

---

src/Microsoft.ServiceFabric.Actors/Runtime/ActorManager.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorReminder.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorReminderData.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ActorReminderState.cs
src/Microsoft.ServiceFabric.Actors/Runtime/KvsActorStateProviderBase.cs
src/Microsoft.ServiceFabric.Actors/Runtime/NullActorStateProvider.cs
src/Microsoft.ServiceFabric.Actors/Runtime/ReliableCollectionsActorStateProvider.cs
src/Microsoft.ServiceFabric.Actors/Runtime/VolatileActorStateProvider.cs

Adding reminder related tracing for following paths - 
- Register Reminder
- Saving reminder in state provider
- Unregister Reminder 
- Firing Reminder 
- Arming Reminder
- Reminder Next Due Time Computation 
- Loading Reminders when actor primary starts/moves

Actor reminders related tracing improvements

---

.github/workflows/build.yml

To enable PR validation builds for all release_* branches in addition to the develop branch.
Also remove v* tag trigger because it's not being used.

Make build.yml trigger for all release_* branches

---

.github/workflows/build.yml

To enable PR validation builds for all release_* branches in addition to the develop branch.
Also remove v* tag trigger because it's not being used.

Make build.yml trigger for all release_* branches in release_7.1

---

.github/workflows/build.yml

To enable PR validation builds for all release_* branches in addition to the develop branch.
Also remove v* tag trigger because it's not being used.

Make build.yml trigger for all release_* branches in release_7.0

---

.github/workflows/build.yml

To enable PR validation builds for all release_* branches in addition to the develop branch.
Also remove v* tag trigger because it's not being used.

Make build.yml trigger for all release_* branches in release_6.1

---

properties/service_fabric_common.props
src/Microsoft.ServiceFabric.Actors.KVSToRCMigration/Microsoft.ServiceFabric.Actors.KVSToRCMigration.csproj
src/Microsoft.ServiceFabric.Services.Remoting/Microsoft.ServiceFabric.Services.Remoting.csproj
src/netstandard/Microsoft.ServiceFabric.Services.Remoting/Microsoft.ServiceFabric.Services.Remoting_netstandard.csproj
test/unittests/Microsoft.ServiceFabric.Actors.StateMigration.Tests/Microsoft.ServiceFabric.Actors.StateMigration.Tests.csproj
test/unittests/Microsoft.ServiceFabric.Actors.Tests/ActorManagerTests.cs
test/unittests/Microsoft.ServiceFabric.Actors.Tests/DependencyInjectionTests.cs
test/unittests/Microsoft.ServiceFabric.Actors.Tests/Microsoft.ServiceFabric.Actors.Tests.csproj
test/unittests/Microsoft.ServiceFabric.Actors.Tests/Runtime/ActorConcurrencyLockTests.cs
test/unittests/Microsoft.ServiceFabric.Actors.Tests/Runtime/IdleObjectGcHandleTests.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/Microsoft.ServiceFabric.Services.Remoting.Tests.csproj
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/SystemExceptionConvertorTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Tests/Microsoft.ServiceFabric.Services.Tests.csproj
test/unittests/Microsoft.ServiceFabric.Services.Tests/StatefulServiceBaseLifeCycleTests.cs
test/unittests/Microsoft.ServiceFabric.Services.Tests/StatelessServiceLifeCycleTests.cs

This repository was flagged for using unsecure Newtonsoft.Json package version through the xunit package dependency. In addition to the xunit packages, upgrade all packages to their latest stable versions.
Dependencies of the shipping product binaries:
- Microsoft.ServiceFabric.Services.Remoting
- System.Reflection.Emit and System.Reflection.Emit.ILGeneration from 4.3.0 to 4.7.0
- System.Diagnostics.DiagnosticSource from 4.3.0 to 8.0.1
Dependencies of the test projects:
- FluentAssertions from 5.9.0 to 6.12.0
- Moq from 4.13.0 to 4.20.70
- Microsoft.NET.Test.Sdk from 15.9.0 to 17.10.0
- xunit from 2.4.1 to 2.8.1
- xunit.runner.visualstudio from 2.4.1 to 2.8.1
- Microsoft.Diagnostics.Tracing.TraceEvent from 2.0.45 to 3.1.12
- System.Net.Http.WinHttpHandler from 6.0.0 to 8.0.0

Update NuGet packages to latest versions

---

nuget.config

Make NuGet.config use the default packageSources instead of clearing the inherited sources and defining the nuget.org feed explicitly. This allows GitHub builds to use the public NuGet.org feed, while the official builds use secure internal feeds instead.

Enable secure NuGet.config in official builds

---

test/unittests/Microsoft.ServiceFabric.Services.Tests/ServicePartitionClientTests.cs

CancelOnTimerWithLargeRetryDelay fails on some environments due 
to the fact that Stopwatch class may report incorrect timing results on 
different processors, as noted in official documentation: 
https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch?view=net-8.0

Fix CancelOnTimerWithLargeRetryDelay test flakiness due to Stopwatch imprecision

---

test/unittests/Microsoft.ServiceFabric.Services.Tests/ServicePartitionClientTests.cs

ServicePartitionClientTests are flaky due to documented imprecision of Stopwatch class.
Based on empirical measurements, we're increasing margin of error from 10ms to 25ms.
Internal ADO work item: https://dev.azure.com/msazure/One/_workitems/edit/29276368

Increase margin of error for Stopwatch based on measurements

---

properties/service_fabric_nuget.props

We need to allow `NuGetPackageVersion` to be provided as an environment variable. 
Currently, the value is unconditionally reassigned to values provided 
in `service_fabric_common.props`:

Avoid overriding NuGetPackageVersion from environment variable

---

src/Microsoft.ServiceFabric.Actors.KVSToRCMigration/Microsoft.ServiceFabric.Actors.KVSToRCMigration.csproj
src/netstandard/Microsoft.ServiceFabric.Actors.KVSToRCMigration/Microsoft.ServiceFabric.Actors.KVSToRCMigration_netstandard.csproj
test/unittests/Microsoft.ServiceFabric.Actors.StateMigration.Tests/Microsoft.ServiceFabric.Actors.StateMigration.Tests.csproj

Overriding versions of transitive dependencies that were flagged as vulnerable on nuget.org.
Internal ADO work item: https://dev.azure.com/msazure/One/_workitems/edit/29603592

Resolving vulnerable transitive dependencies

---

.github/workflows/build.yml
buildAll.proj
test/unittests/Microsoft.ServiceFabric.Actors.StateMigration.Tests/Microsoft.ServiceFabric.Actors.StateMigration.Tests.csproj
test/unittests/Microsoft.ServiceFabric.Actors.Tests/Microsoft.ServiceFabric.Actors.Tests.csproj
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/Microsoft.ServiceFabric.Services.Remoting.Tests.csproj
test/unittests/Microsoft.ServiceFabric.Services.Tests/Microsoft.ServiceFabric.Services.Tests.csproj

This PR enables tests for .NET 9 builds. 
Compatibility with the deprecated BinaryFormatter has been introduced so that .NET 9 tests can be enabled.
Additionally, we are moving away from the `buils.ps1` script, which uses `msbuild` under the hood. Instead, we are moving to the `dotnet` tool, in the aim of streamlining the build process and infrastructure. 
Internal ADO work item: https://dev.azure.com/msazure/One/_workitems/edit/29603235

Enabling .NET 9 tests for SF SDK packages

---

.github/workflows/build.yml
code.sln
properties/service_fabric_common.props
src/FabActUtil/Microsoft.ServiceFabric.Actors.targets
src/FabActUtil/Program.cs
src/Microsoft.ServiceFabric.Actors/Remoting/ActorRemotingProviderAttribute.cs
src/Microsoft.ServiceFabric.Services.Remoting/ServiceRemotingProviderAttribute.cs
test/netfx/Microsoft.ServiceFabric.Actors.Tests/Microsoft.ServiceFabric.Actors.Tests_netfx.csproj
test/netfx/Microsoft.ServiceFabric.Services.Remoting.Tests/Microsoft.ServiceFabric.Services.Remoting.Tests_netfx.csproj
test/unittests/Microsoft.ServiceFabric.Actors.Tests/ActorRemotingProviderAttributeTest.cs
test/unittests/Microsoft.ServiceFabric.Actors.Tests/AssemblyAttributes.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/ServiceRemotingProviderAttributeTest.cs

- Restore original behavior of the `ActorRemotingProviderAttribute` and `ServiceRemotingProviderAttribute` on NetStandard so that explicitly specifying a redundant assembly attribute is not required. The attribute is now required only on NetFx.
- Create NetFx test projects with the minimum set of tests for now to verify new NetFx behavior.
- Make build.yml use pre-installed .NET 9 and disable strong name verification to enable testing of the delay-signed NetFx assemblies.
- Make remoting provider error messages more descriptive.
- Make FabActUtil report exception messages as build errors and stack trace as build messages.
- Increment build number for integration in WindowsFabric repo.

Fix unexpected Remoting V1 deprecation errors

---

properties/service_fabric_common.props
src/Microsoft.ServiceFabric.Services.Remoting/FabricTransport/FabricTransportRemotingSettings.cs
src/Microsoft.ServiceFabric.Services.Remoting/FabricTransport/Runtime/FabricTransportRemotingListenerSettings.cs
src/Microsoft.ServiceFabric.Services.Remoting/RemotingClientVersion.cs
src/Microsoft.ServiceFabric.Services.Remoting/RemotingListenerVersion.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/Client/ExceptionConversionHandler.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/FabricTransport/Runtime/FabricTransportServiceRemotingListener.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/Runtime/ExceptionConversionHandler.cs
test/unittests/Microsoft.ServiceFabric.Actors.Tests/ExceptionConvertors/FabricActorExceptionTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/CompatScenarioTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/CustomConvertorTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/FabricExceptionConvertorTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/SystemExceptionConvertorTest.cs

- Deprecate the `ExceptionDeserializationTechnique` property of the `FabricTransportRemotingSettings` and change its default value from `Fallback` to `Default`. 
- Deprecate the `ExceptionSerializationTechnique` property of the `FabricTransportListenerSettings` and change its default value from `BinaryFormatter` to `Default`.

 Make exception serialization settings used by Remoting secure by default

---

Directory.Packages.props

These packages need to consume the next major version of the Service Fabric runtime so then their dependencies point to version 12 of it.  Then the packages that are generated from this build are consumed by the Service Fabric runtime.

Increment package dependencies for major version increase of Service Fabric runtime

---

Directory.Packages.props
properties/service_fabric_common.props

We need these changes in order to move ServiceFabric project to new major version (12). We also need to bump the package version to 9.2.0. in order to build the new nuget package.

Introduce changes needed for SF12 into release9.0

---

src/Microsoft.ServiceFabric.Services.Remoting/FabricTransport/Runtime/FabricTransportRemotingListenerSettings.cs

Index in format string must not be larger than the size of the argument list.
String formatter throws exception here.

Fix trace printout in FabricTransportRemotingListenerSettings

---

.editorconfig
src/Microsoft.ServiceFabric.Actors/Diagnostics/ActorFrameworkEventSource.cs
src/Microsoft.ServiceFabric.Services/Runtime/ServiceFrameworkEventSource.cs
test/unittests/Microsoft.ServiceFabric.Actors.Tests/ActorEventSourceTest.cs
test/unittests/Microsoft.ServiceFabric.Actors.Tests/Diagnostics/ActorFrameworkEventSourceTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Tests/Runtime/ServiceFrameworkEventSourceTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Tests/ServiceEventSourceTest.cs

Create initial tests for the EventSource classes to document the dynamically-generated GUIDs in the code and save the instrumentation manifests for inspection and registration with the ETL tools, like Event Viewer and PerfView.

Document GUIDs and manifests of the EventSource classes

---

test/unittests/Microsoft.ServiceFabric.Actors.Tests/Runtime/Volatile/VolatileActorStateTableTests.cs

Incorrect spelling of the word committed

Fix typos in VolatileActorStateTableTests names

---

properties/service_fabric_common.props
src/Microsoft.ServiceFabric.Actors/FabricActorExceptionKnownTypes.cs
src/Microsoft.ServiceFabric.Actors/SR.Designer.cs
src/Microsoft.ServiceFabric.Actors/SR.resx
src/Microsoft.ServiceFabric.Services.Remoting/FabricTransport/Runtime/FabricTransportRemotingListenerSettings.cs
src/Microsoft.ServiceFabric.Services.Remoting/SR.resx
src/Microsoft.ServiceFabric.Services.Remoting/V2/FabricExceptionKnownTypes.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/FabricTransport/Client/FabricTransportServiceRemotingClientFactory.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/Messaging/BufferPoolManager.cs
src/Microsoft.ServiceFabric.Services.Remoting/V2/SystemExceptionKnownTypes.cs
src/Microsoft.ServiceFabric.Services/Communication/Runtime/ServiceReplicaListener.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/FabricExceptionConvertorTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Remoting.Tests/V2/ExceptionConvertors/SystemExceptionConvertorTest.cs
test/unittests/Microsoft.ServiceFabric.Services.Tests/ServiceNameFormatTests.cs

Add following exceptions classes to lists of System and Fabric known exceptions:
* `System.Threading.Tasks.TaskCanceledException`
* `System.Fabric.FabricInsufficientMaxLoadCapacityException`
* `System.Fabric.FabricSkipRestoreOperationException`
* `System.Fabric.FabricBackupNotFoundException`
Bump minor version (`12.3.0` -> `12.4.0`).
Several minor fixes (proper order of using directives and name spaces, several typos fixed).

Add new System and Fabric known exceptions

---

nuget.config

Make NuGet.config use the default packageSources instead of clearing the inherited sources and defining the nuget.org feed explicitly. This allows GitHub builds to use the public NuGet.org feed, while the official builds use secure internal feeds instead.

Fix ADO build for release_7.1
